from .event_handler import KeyboardEventHandler, MouseEventHandler
from ..input import KeyboardCode, MouseCode, KeyboardEvent, MouseEvent


class EventHandlers:
    SHIFT_BACKSPACE = KeyboardEventHandler.default(KeyboardCode.SHIFT_BACKSPACE)
    TAB = KeyboardEventHandler.default(KeyboardCode.TAB)
    ENTER = KeyboardEventHandler.default(KeyboardCode.ENTER)
    BACKSPACE = KeyboardEventHandler.default(KeyboardCode.BACKSPACE)
    POUND = KeyboardEventHandler.default(KeyboardCode.POUND)

    UP_ARROW = KeyboardEventHandler.default(KeyboardCode.UP_ARROW)
    DOWN_ARROW = KeyboardEventHandler.default(KeyboardCode.DOWN_ARROW)
    RIGHT_ARROW = KeyboardEventHandler.default(KeyboardCode.RIGHT_ARROW)
    LEFT_ARROW = KeyboardEventHandler.default(KeyboardCode.LEFT_ARROW)
    END = KeyboardEventHandler.default(KeyboardCode.END)
    HOME = KeyboardEventHandler.default(KeyboardCode.HOME)
    SHIFT_TAB = KeyboardEventHandler.default(KeyboardCode.SHIFT_TAB)

    INSERT = KeyboardEventHandler.default(KeyboardCode.INSERT)
    DELETE = KeyboardEventHandler.default(KeyboardCode.DELETE)
    PAGE_UP = KeyboardEventHandler.default(KeyboardCode.PAGE_UP)
    PAGE_DOWN = KeyboardEventHandler.default(KeyboardCode.PAGE_DOWN)
    F5 = KeyboardEventHandler.default(KeyboardCode.F5)
    F6 = KeyboardEventHandler.default(KeyboardCode.F6)
    F7 = KeyboardEventHandler.default(KeyboardCode.F7)
    F8 = KeyboardEventHandler.default(KeyboardCode.F8)
    F9 = KeyboardEventHandler.default(KeyboardCode.F9)
    F10 = KeyboardEventHandler.default(KeyboardCode.F10)
    F11 = KeyboardEventHandler.default(KeyboardCode.F11)
    F12 = KeyboardEventHandler.default(KeyboardCode.F12)

    F1 = KeyboardEventHandler.default(KeyboardCode.F1)
    F2 = KeyboardEventHandler.default(KeyboardCode.F2)
    F3 = KeyboardEventHandler.default(KeyboardCode.F3)
    F4 = KeyboardEventHandler.default(KeyboardCode.F4)
    SPACE = KeyboardEventHandler.default(" ")
    FORWARD_SLASH = KeyboardEventHandler.default("/")
    BACKSLASH = KeyboardEventHandler.default("\\")
    VERTICAL_BAR = KeyboardEventHandler.default("|")
    PIPE = KeyboardEventHandler.default("|")
    EXCLAMATION_MARK = KeyboardEventHandler.default("!")
    QUESTION_MARK = KeyboardEventHandler.default("?")
    COMMA = KeyboardEventHandler.default(",")
    FULL_STOP = KeyboardEventHandler.default(".")
    LESS_THAN = KeyboardEventHandler.default("<")
    LEFT_ANGLE_BRACKET = KeyboardEventHandler.default("<")
    LEFT_CHEVRON = KeyboardEventHandler.default("<")
    GREATER_THAN = KeyboardEventHandler.default(">")
    RIGHT_ANGLE_BRACKET = KeyboardEventHandler.default(">")
    RIGHT_CHEVRON = KeyboardEventHandler.default(">")
    SEMI_COLON = KeyboardEventHandler.default(";")
    COLON = KeyboardEventHandler.default(":")
    APOSTROPHE = KeyboardEventHandler.default("'")
    AT = KeyboardEventHandler.default("@")
    HASHTAG = KeyboardEventHandler.default("#")
    OCTOTHORPE = KeyboardEventHandler.default("#")
    TILDE = KeyboardEventHandler.default("~")
    LEFT_SQUARE_BRACKET = KeyboardEventHandler.default("[")
    RIGHT_SQUARE_BRACKET = KeyboardEventHandler.default("]")
    LEFT_CURLY_BRACKET = KeyboardEventHandler.default("{")
    LEFT_BRACE = KeyboardEventHandler.default("{")
    RIGHT_CURLY_BRACKET = KeyboardEventHandler.default("}")
    RIGHT_BRACE = KeyboardEventHandler.default("}")
    HYPHEN = KeyboardEventHandler.default("-")
    MINUS = KeyboardEventHandler.default("-")
    UNDERSCORE = KeyboardEventHandler.default("_")
    EQUALS = KeyboardEventHandler.default("=")
    PLUS = KeyboardEventHandler.default("+")
    BACKTICK = KeyboardEventHandler.default("`")
    LOGICAL_NEGATION = KeyboardEventHandler.default("¬")
    BROKEN_BAR = KeyboardEventHandler.default("¦")
    SPEECH_MARK = KeyboardEventHandler.default("\")")
    QUOTATION_MARK = KeyboardEventHandler.default("\")")
    DOLLAR = KeyboardEventHandler.default("$")
    PERCENT = KeyboardEventHandler.default("%")
    CARET = KeyboardEventHandler.default("^")
    AMPERSAND = KeyboardEventHandler.default("&")
    ASTERISK = KeyboardEventHandler.default("*")
    LEFT_BRACKET = KeyboardEventHandler.default("(")
    LEFT_PARENTHESIS = KeyboardEventHandler.default("(")
    RIGHT_BRACKET = KeyboardEventHandler.default(")")
    RIGHT_PARENTHESIS = KeyboardEventHandler.default(")")

    LEFT_MOUSE_UP = MouseEventHandler.default(MouseCode.LEFT_MOUSE_UP)
    LEFT_MOUSE_DOWN = MouseEventHandler.default(MouseCode.LEFT_MOUSE_DOWN)
    MIDDLE_MOUSE_UP = MouseEventHandler.default(MouseCode.MIDDLE_MOUSE_UP)
    MIDDLE_MOUSE_DOWN = MouseEventHandler.default(MouseCode.MIDDLE_MOUSE_DOWN)
    RIGHT_MOUSE_UP = MouseEventHandler.default(MouseCode.RIGHT_MOUSE_UP)
    RIGHT_MOUSE_DOWN = MouseEventHandler.default(MouseCode.RIGHT_MOUSE_DOWN)
    LEFT_MOUSE_DRAG = MouseEventHandler.default(MouseCode.LEFT_MOUSE_DRAG)
    MIDDLE_MOUSE_DRAG = MouseEventHandler.default(MouseCode.MIDDLE_MOUSE_DRAG)
    RIGHT_MOUSE_DRAG = MouseEventHandler.default(MouseCode.RIGHT_MOUSE_DRAG)
    MOUSE_MOVE = MouseEventHandler.default(MouseCode.MOVE)
    MOUSE_SCROLL_UP = MouseEventHandler.default(MouseCode.SCROLL_UP)
    MOUSE_SCROLL_DOWN = MouseEventHandler.default(MouseCode.SCROLL_DOWN)

    ANY_KEYBOARD = KeyboardEventHandler(lambda _, __: True)
    ANY_MOUSE = MouseEventHandler(lambda _, __: True)
    UNRECOGNIZED_KEYBOARD = KeyboardEventHandler.default(KeyboardEvent.UNRECOGNIZED_NAME)
    UNRECOGNIZED_MOUSE = KeyboardEventHandler.default(MouseEvent.UNRECOGNIZED_NAME)
